export const ROUTES = {
  HOME: '/',
  ARTISTS: '/artists',
  ARTIST_DETAIL: (id) => `/artists/${id}`,
  CONCERTS: '/concerts',
  CONCERT_DETAIL: (id) => `/concerts/${id}`,
  RELEASES: '/releases',
  RELEASE_DETAIL: (id) => `/releases/${id}`,
  CALENDAR: '/calendar',
  SEARCH: '/search',
  MY: '/my',
  ADMIN: '/admin',
  ADMIN_ARTIST_NEW: '/admin/artists/new',
  ADMIN_ARTIST_EDIT: (id) => `/admin/artists/${id}/edit`,
  ADMIN_CONCERT_NEW: '/admin/concerts/new',
  ADMIN_CONCERT_EDIT: (id) => `/admin/concerts/${id}/edit`,
  ADMIN_INQUIRIES: '/admin/inquiries',
}
